# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created: Mon Oct 20 10:37:57 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(603, 275)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_grass = QtGui.QLabel(Dialog)
        self.label_grass.setObjectName(_fromUtf8("label_grass"))
        self.horizontalLayout.addWidget(self.label_grass)
        self.lineEdit_grass = QtGui.QLineEdit(Dialog)
        self.lineEdit_grass.setObjectName(_fromUtf8("lineEdit_grass"))
        self.horizontalLayout.addWidget(self.lineEdit_grass)
        self.pushButton_grass = QtGui.QPushButton(Dialog)
        self.pushButton_grass.setObjectName(_fromUtf8("pushButton_grass"))
        self.horizontalLayout.addWidget(self.pushButton_grass)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_grassdata = QtGui.QLabel(Dialog)
        self.label_grassdata.setObjectName(_fromUtf8("label_grassdata"))
        self.horizontalLayout_6.addWidget(self.label_grassdata)
        self.lineEdit_grassdata = QtGui.QLineEdit(Dialog)
        self.lineEdit_grassdata.setObjectName(_fromUtf8("lineEdit_grassdata"))
        self.horizontalLayout_6.addWidget(self.lineEdit_grassdata)
        self.pushButton_grassdata = QtGui.QPushButton(Dialog)
        self.pushButton_grassdata.setObjectName(_fromUtf8("pushButton_grassdata"))
        self.horizontalLayout_6.addWidget(self.pushButton_grassdata)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_grasslocation = QtGui.QLabel(Dialog)
        self.label_grasslocation.setObjectName(_fromUtf8("label_grasslocation"))
        self.horizontalLayout_7.addWidget(self.label_grasslocation)
        self.lineEdit_grasslocation = QtGui.QLineEdit(Dialog)
        self.lineEdit_grasslocation.setObjectName(_fromUtf8("lineEdit_grasslocation"))
        self.horizontalLayout_7.addWidget(self.lineEdit_grasslocation)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_gdal = QtGui.QLabel(Dialog)
        self.label_gdal.setObjectName(_fromUtf8("label_gdal"))
        self.horizontalLayout_3.addWidget(self.label_gdal)
        self.lineEdit_gdal = QtGui.QLineEdit(Dialog)
        self.lineEdit_gdal.setObjectName(_fromUtf8("lineEdit_gdal"))
        self.horizontalLayout_3.addWidget(self.lineEdit_gdal)
        self.pushButton_gdal = QtGui.QPushButton(Dialog)
        self.pushButton_gdal.setObjectName(_fromUtf8("pushButton_gdal"))
        self.horizontalLayout_3.addWidget(self.pushButton_gdal)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_liblas = QtGui.QLabel(Dialog)
        self.label_liblas.setObjectName(_fromUtf8("label_liblas"))
        self.horizontalLayout_4.addWidget(self.label_liblas)
        self.lineEdit_liblas = QtGui.QLineEdit(Dialog)
        self.lineEdit_liblas.setObjectName(_fromUtf8("lineEdit_liblas"))
        self.horizontalLayout_4.addWidget(self.lineEdit_liblas)
        self.pushButton_liblas = QtGui.QPushButton(Dialog)
        self.pushButton_liblas.setObjectName(_fromUtf8("pushButton_liblas"))
        self.horizontalLayout_4.addWidget(self.pushButton_liblas)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_pdal = QtGui.QLabel(Dialog)
        self.label_pdal.setObjectName(_fromUtf8("label_pdal"))
        self.horizontalLayout_5.addWidget(self.label_pdal)
        self.lineEdit_pdal = QtGui.QLineEdit(Dialog)
        self.lineEdit_pdal.setObjectName(_fromUtf8("lineEdit_pdal"))
        self.horizontalLayout_5.addWidget(self.lineEdit_pdal)
        self.pushButton_pdal = QtGui.QPushButton(Dialog)
        self.pushButton_pdal.setObjectName(_fromUtf8("pushButton_pdal"))
        self.horizontalLayout_5.addWidget(self.pushButton_pdal)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_proj = QtGui.QLabel(Dialog)
        self.label_proj.setObjectName(_fromUtf8("label_proj"))
        self.horizontalLayout_8.addWidget(self.label_proj)
        self.lineEdit_proj = QtGui.QLineEdit(Dialog)
        self.lineEdit_proj.setObjectName(_fromUtf8("lineEdit_proj"))
        self.horizontalLayout_8.addWidget(self.lineEdit_proj)
        self.pushButton_proj = QtGui.QPushButton(Dialog)
        self.pushButton_proj.setObjectName(_fromUtf8("pushButton_proj"))
        self.horizontalLayout_8.addWidget(self.pushButton_proj)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_epsg = QtGui.QLabel(Dialog)
        self.label_epsg.setObjectName(_fromUtf8("label_epsg"))
        self.horizontalLayout_2.addWidget(self.label_epsg)
        self.epsg = QtGui.QLineEdit(Dialog)
        self.epsg.setObjectName(_fromUtf8("epsg"))
        self.horizontalLayout_2.addWidget(self.epsg)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok|QtGui.QDialogButtonBox.Save)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "STEM impostazioni", None))
        self.label_grass.setText(_translate("Dialog", "Percorso all\'eseguibile di GRASS GIS 7", None))
        self.pushButton_grass.setText(_translate("Dialog", "Sfoglia", None))
        self.label_grassdata.setText(_translate("Dialog", "Percorso alla GRASSDATA directory", None))
        self.pushButton_grassdata.setText(_translate("Dialog", "Sfoglia", None))
        self.label_grasslocation.setText(_translate("Dialog", "Nome della location da utilizzare", None))
        self.label_gdal.setText(_translate("Dialog", "Percorso all\'eseguibile di GDAL", None))
        self.pushButton_gdal.setText(_translate("Dialog", "Sfoglia", None))
        self.label_liblas.setText(_translate("Dialog", "Percorso all\'eseguibile di libLAS", None))
        self.pushButton_liblas.setText(_translate("Dialog", "Sfoglia", None))
        self.label_pdal.setText(_translate("Dialog", "Percorso all\'eseguibile di PDAL", None))
        self.pushButton_pdal.setText(_translate("Dialog", "Sfoglia", None))
        self.label_proj.setText(_translate("Dialog", "Percorso alla directory di PROJ", None))
        self.pushButton_proj.setText(_translate("Dialog", "Sfoglia", None))
        self.label_epsg.setText(_translate("Dialog", "Codice EPSG da utilizzare", None))

